# -*- coding: utf-8 -*-
"""
Created on Sat Apr 25 11:00:34 2020

@author: Sam
"""
from mingus.midi import midi_file_out, midi_file_in


# Load midi generated by Lilypond (Frescobaldi)
y_comp, y_bpm = midi_file_in.MIDI_to_Composition(r'C:\Users\Sam\Documents\Sidewinder\sidewinder\Lilypond\references\1-120.mid')

# Re-export as midi for validation
midi_file_out.write_Composition(r'C:\Users\Sam\Documents\Sidewinder\sidewinder\Lilypond\references\1-120_out.mid', 
                                y_comp, repeat=0, verbose=True)
